### ISSUE TITLE
コメントへのいいねの実装

### ISSUE THREAD

**Issue by katoatsushi** [team-tissis/cInsightBackend#11]
[現状]
Commentテーブルに int 型 で `favo` というカラムがあり、コメントにfavoされるたびに `favo` カラムの値が1増える仕様
[問題]
- いいねを取り消せない
- 誰から貰ったいいねなのか追えない

[理想]
どのコメントにいいねを貰ったか管理する中間テーブルを作成する

- テーブル構成は以下
(もし、コメントに対するいいねをその都度オンチェーンに保存する場合は `is_synced` カラムは不必要)
```
class CommentFavorite(models.Model):
    user = models.ForeignKey(CustomeUser, on_delete=models.CASCADE, null=False, related_name="comment_favorites")
    comment = models.ForeignKey(Lecture, on_delete=models.CASCADE, null=True, related_name="comment_favorites")
    is_synced = models.BooleanField(help_text='オンチェーンにデータを保存できたらTrue', default=False)
    vote_weight = models.IntegerField(default=1, help_text='1つあたりのいいねの重み')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
```

(もし、コメントに対するいいねをその都度オンチェーンに保存する場合は `※` がついた部分は不必要)
- 作成すべきAPI
[GET] あるコメントに幾ついいねがあるかを取得するAPI 、受け取る値は (`comment_id`)、返り値は`いいね合計カウント値`など
※ [POST] いいねを作成するAPI、受け取る値は (`eoa`, `comment_id`)、返り値はなんでも良い
※ [POST] オンチェーンに保存されていないいいね一覧を取得するAPI、受け取る値は (`eoa`)、返り値はいいねの配列
[PUT] いいねをオンチェーンに保存後レコードを更新するAPI、受け取る値は ( `comment_favorite_id`)、返り値はなんでも良い

参考: https://www.notion.so/standard2017cojp/4f04c2bebbaa47a8b2b36f2c1be9dad3

フロント側に必要な修正は別途記載

**Comment by hidenoriwakiri** [comment]
中間テーブルを作らずとも、Favorite テーブルを改変することで、要件を全て満たした実装ができる気がしたんだけど、意見聞きたいです。

## 前提
- lecture へのいいねと comment へのいいねは基本的に同等のものとして扱われます。
## 実装方法
- Favorite テーブルに、誰からのファボかと誰へのファボか (現状は後者だけ保持と認識) を入れておけば、いいねボタンが押されるたびに、Favorite のレコードを追加すれば ok なはずで、これにより、ユーザーが1ヶ月間に送ったファボともらったファボの数も取得できるはず。
- 勿論、バックのみならずフロントも大きな改修が必要になります。
- あっちゃんの押せるいいね数に上限を設けるタスクと、重複が多いと思うので、適宜タスク細分化、割り振りする必要があるかもしれない。
https://github.com/team-tissis/cInsightBackend/blob/develop/api/models/favorite.py

**Comment by hidenoriwakiri** [comment]
@

**Comment by hidenoriwakiri** [comment]
@katoatsushi

**Comment by katoatsushi** [comment]
@hidenoriwakiri 
勉強会に対するいいねがいくつかみたいなのは表示できなくなるけど、それでも良さそう🙆
![Screenshot 2023-04-27 at 12 50 21](https://user-images.githubusercontent.com/42636663/234755194-1e32a05e-f9d0-4d83-b733-4d853c90a999.png)

**Comment by katoatsushi** [comment]
既存のFavoriteにフラグを立てて、コメントのいいねなのか勉強会のいいねなのか分別させる
[現状]
```
class Favorite(models.Model):
    user = models.ForeignKey(CustomeUser, on_delete=models.CASCADE, null=False, related_name="favorites")
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE, null=False, related_name="favorites")
    is_synced = models.BooleanField(help_text='オンチェーンにデータを保存できたらTrue', default=False)
    vote_weight = models.IntegerField(default=1)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
```
[変更後]
```
class Favorite(models.Model):
    user = models.ForeignKey(CustomeUser, on_delete=models.CASCADE, null=False, related_name="favorites")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="favorites")
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE, related_name="favorites")
    is_synced = models.BooleanField(help_text='オンチェーンにデータを保存できたらTrue', default=False)
    kind = models.IntegerField(default=1)
    vote_weight = models.IntegerField(default=1)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
```
に変更すれば良さそう
kind == 1 の時は、lectureに値が入り
kind ==2 の時は、commentに値が入る

**Comment by katoatsushi** [comment]
`api/view/favorite_view.py`にて `create` が変更が必要

`create関数`
```
        lectureId = request.data.get("id")  # lecture_id => id に変更
        eoa = request.data.get("eoa")
        kind = request.data.get("kind")  # 追加する
        if (kind == "comment"):
             # コメントに関連するFavoを作成する
        elif  (kind == "lecture"):
```

**Comment by katoatsushi** [comment]
@hidenoriwakiri

**Comment by hidenoriwakiri** [comment]
実装方法が変わったので、解決。クローズします。
